CREATE TABLE PCMAEBACKENDS (
  id VARCHAR(50),
  url VARCHAR(250),
  account VARCHAR(50),
  username VARCHAR(50),
  password VARCHAR(250),
  PRIMARY KEY(id)
) ENGINE=INNODB;

CREATE TABLE PLUGINS (
  id VARCHAR(50),
  className VARCHAR(250),
  source VARCHAR(250),
  pcmaeBackendId VARCHAR(50),
  PRIMARY KEY (id),
  FOREIGN KEY (pcmaeBackendId) REFERENCES PCMAEBACKENDS(id) ON DELETE RESTRICT
) ENGINE=INNODB;


CREATE TABLE CLUSTERS (
  id VARCHAR(36) NOT NULL,
  owner VARCHAR(36),
  name VARCHAR(250),
  description VARCHAR(250),
  clusterId VARCHAR(250),
  size INTEGER,
  state INTEGER,
  launchTime BIGINT,
  terminateTime BIGINT,
  PRIMARY KEY (id)
) ENGINE=INNODB;


CREATE TABLE SOFTLAYERACCOUNTS (
  id 			VARCHAR(36) NOT NULL,
  url			VARCHAR(50),
  username		VARCHAR(64),
  apiKey 		VARCHAR(128),
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE GATEWAYS (
  id VARCHAR(36) NOT NULL,
  softLayerId	INTEGER,
  username		VARCHAR(25),
  password		VARCHAR(50),
  subscriberId		VARCHAR(36),
  type			VARCHAR(10),
  softLayerAccountId  VARCHAR(36),	
  PRIMARY KEY (id),
  FOREIGN KEY (subscriberId) REFERENCES SUBSCRIBERS(id) ON DELETE CASCADE,
  FOREIGN KEY (softLayerAccountId) REFERENCES SOFTLAYERACCOUNTS(id) ON DELETE RESTRICT
) ENGINE=INNODB;

CREATE TABLE VLANS (
  id VARCHAR(36) NOT NULL,
  softLayerId	INTEGER,
  subscriberId	VARCHAR(36),
  gatewayId		VARCHAR(36),
  vlanNumber    VARCHAR(36),
  softLayerAccountId  VARCHAR(36),
  PRIMARY KEY (id),
  FOREIGN KEY (gatewayId) REFERENCES GATEWAYS(id),
  FOREIGN KEY (subscriberId) REFERENCES SUBSCRIBERS(id),
  FOREIGN KEY (softLayerAccountId) REFERENCES SOFTLAYERACCOUNTS(id) ON DELETE RESTRICT
) ENGINE=INNODB;

CREATE TABLE SUBNETS (
  id VARCHAR(36) NOT NULL,
  softLayerId	INTEGER,
  vlanId		VARCHAR(36) NOT NULL,
  networkAddr	VARCHAR(15),
  gatewayAddr	VARCHAR(15),
  broadcastAddr	VARCHAR(15),
  cidr			INTEGER,
  softLayerAccountId  VARCHAR(36),
  PRIMARY KEY (id),
  FOREIGN KEY (vlanId) REFERENCES VLANS(id) ON DELETE CASCADE,
  FOREIGN KEY (softLayerAccountId) REFERENCES SOFTLAYERACCOUNTS(id) ON DELETE RESTRICT
) ENGINE=INNODB;

CREATE TABLE IPADDRESS (
  id VARCHAR(36) NOT NULL,
  ipAddress 	BIGINT NOT NULL,
  subnetId		VARCHAR(36) NOT NULL,
  hostname		VARCHAR(64),
  clusterId		VARCHAR(36),
  tierName		VARCHAR(50),
  PRIMARY KEY (id),
  FOREIGN KEY (subnetId) REFERENCES SUBNETS(id) ON DELETE CASCADE,
  FOREIGN KEY (clusterId) REFERENCES CLUSTERS(id) ON DELETE CASCADE
) ENGINE=INNODB;

